ALTER TABLE "Presupuesto"
ADD COLUMN "descuentoPorcentaje" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "descuentoImporte" DOUBLE PRECISION NOT NULL DEFAULT 0;

ALTER TABLE "Factura"
ADD COLUMN "descuentoPorcentaje" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "descuentoImporte" DOUBLE PRECISION NOT NULL DEFAULT 0;
